// Server Link

export const link = "https://walletappmanagement.herokuapp.com/api";

//Alert 

export const SET_ALERT = "SET_ALERT";
export const  REMOVE_ALERT = " REMOVE_ALERT";

// Auth

// Sign In

export const SIGN_IN_REQUEST = "SIGN_IN_REQUEST";
export const SIGN_IN_SUCCESS = "SIGN_IN_SUCCESS";
export const SIGN_IN_FAIL = "SIGN_IN_FAIL";

//Sign Up

export const SIGN_UP_REQUEST = "SIGN_UP_REQUEST";
export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS";
export const SIGN_UP_FAIL = "SIGN_UP_FAIL";

// Get user details

export const GET_USER_REQUEST = "GET_USER_REQUEST";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_FAIL = "GET_USER_FAIL";

// INCOME 

// Create Borrowing

export const CREATE_BORROWING_REQUEST = "CREATE_BORROWING_REQUEST";
export const CREATE_BORROWING_SUCCESS = "CREATE_BORROWING_SUCCESS";
export const CREATE_BORROWING_FAIL = "CREATE_BORROWING_FAIL";

// Get the last 20 Borrowing 

export const GET_BORROWING_REQUEST = "GET_BORROWING_REQUEST";
export const GET_BORROWING_SUCCESS = "GET_BORROWING_SUCCESS";
export const GET_BORROWING_FAIL = "GET_BORROWING_FAIL";

//select borrowing
export const SELECTED_BORROWING_REQUEST = "SELECTED_BORROWING_REQUEST";
export const SELECTED_BORROWING_SUCCESS = "SELECTED_BORROWING_SUCCESS";
export const SELECTED_BORROWING_FAIL = "SELECTED_BORROWING_FAIL";

// Get a specific borrowing 

export const FILTER_BY_ID_BORROWING_REQUEST = "FILTER_BY_ID_BORROWING_REQUEST";
export const FILTER_BY_ID_BORROWING_SUCCESS = "FILTER_BY_ID_BORROWING_SUCCESS";
export const FILTER_BY_ID_BORROWING_FAIL = "FILTER_BY_ID_BORROWING_FAIL";

//Delete Borrowing

export const DELETE_BORROWING_REQUEST = "DELETE_BORROWING_REQUEST";
export const DELETE_BORROWING_SUCCESS = "DELETE_BORROWING_SUCCESS";
export const DELETE_BORROWING_FAIL = "DELETE_BORROWING_FAIL";

// Filter Borrowing

export const FILTER_BORROWING_REQUEST = "FILTER_BORROWING_REQUEST";
export const FILTER_BORROWING_SUCCESS = "FILTER_BORROWING_SUCCESS";
export const FILTER_BORROWING_FAIL = "FILTER_BORROWING_FAIL";

export const FILTER_TOTAL_AMOUNT_BORROWING_BY_CURRENCY_REQUEST = "FILTER_TOTAL_AMOUNT_BORROWING_BY_CURRENCY_REQUEST";
export const FILTER_TOTAL_AMOUNT_BORROWING_BY_CURRENCY_SUCCESS = "FILTER_TOTAL_AMOUNT_BORROWING_BY_CURRENCY_SUCCESS";
export const FILTER_TOTAL_AMOUNT_BORROWING_BY_CURRENCY_FAIL = "FILTER_TOTAL_AMOUNT_BORROWING_BY_CURRENCY_FAIL";

export const TOTAL_AMOUNT_OF_THE_LAST_SIX_MONTH_BY_CURRENCY_REQUEST = "TOTAL_AMOUNT_OF_THE_LAST_SIX_MONTH_BY_CURRENCY_REQUEST";
export const TOTAL_AMOUNT_OF_THE_LAST_SIX_MONTH_BY_CURRENCY_SUCCESS = "TOTAL_AMOUNT_OF_THE_LAST_SIX_MONTH_BY_CURRENCY_SUCCESS";
export const TOTAL_AMOUNT_OF_THE_LAST_SIX_MONTH_BY_CURRENCY_FAIL = "TOTAL_AMOUNT_OF_THE_LAST_SIX_MONTH_BY_CURRENCY_FAIL";

// Loan 

// Create loan

export const CREATE_LOAN_REQUEST = "CREATE_LOAN_REQUEST";
export const CREATE_LOAN_SUCCESS = "CREATE_LOAN_SUCCESS";
export const CREATE_LOAN_FAIL = "CREATE_LOAN_FAIL";

// Get the last 20 loans 

export const GET_LOAN_REQUEST = "GET_LOAN_REQUEST";
export const GET_LOAN_SUCCESS = "GET_LOAN_SUCCESS";
export const GET_LOAN_FAIL = "GET_LOAN_FAIL";

// Get a specific loan 

export const FILTER_BY_ID_LOAN_REQUEST = "FILTER_BY_ID_LOAN_REQUEST";
export const FILTER_BY_ID_LOAN_SUCCESS = "FILTER_BY_ID_LOAN_SUCCESS";
export const FILTER_BY_ID_LOAN_FAIL = "FILTER_BY_ID_LOAN_FAIL";

//Delete loan

export const DELETE_LOAN_REQUEST = "DELETE_LOAN_REQUEST";
export const DELETE_LOAN_SUCCESS = "DELETE_LOAN_SUCCESS";
export const DELETE_LOAN_FAIL = "DELETE_LOAN_FAIL";

// Filter loan

export const FILTER_LOAN_REQUEST = "FILTER_LOAN_REQUEST";
export const FILTER_LOAN_SUCCESS = "FILTER_LOAN_SUCCESS";
export const FILTER_LOAN_FAIL = "FILTER_LOAN_FAIL";

//select Loan
export const SELECTED_LOAN_REQUEST = "SELECTED_LOAN_REQUEST";
export const SELECTED_LOAN_SUCCESS = "SELECTED_LOAN_SUCCESS";
export const SELECTED_LOAN_FAIL = "SELECTED_LOAN_FAIL";

export const FILTER_TOTAL_AMOUNT_LOAN_BY_CURRENCY_REQUEST = "FILTER_TOTAL_AMOUNT_LOAN_BY_CURRENCY_REQUEST";
export const FILTER_TOTAL_AMOUNT_LOAN_BY_CURRENCY_SUCCESS = "FILTER_TOTAL_AMOUNT_LOAN_BY_CURRENCY_SUCCESS";
export const FILTER_TOTAL_AMOUNT_LOAN_BY_CURRENCY_FAIL = "FILTER_TOTAL_AMOUNT_LOAN_BY_CURRENCY_FAIL";

// Expense 

// Create expense

export const CREATE_EXPENSE_REQUEST = "CREATE_EXPENSE_REQUEST";
export const CREATE_EXPENSE_SUCCESS = "CREATE_EXPENSE_SUCCESS";
export const CREATE_EXPENSE_FAIL = "CREATE_EXPENSE_FAIL";

// Get the last 20 expense 

export const GET_EXPENSE_REQUEST = "GET_EXPENSE_REQUEST";
export const GET_EXPENSE_SUCCESS = "GET_EXPENSE_SUCCESS";
export const GET_EXPENSE_FAIL = "GET_EXPENSE_FAIL";

// Get a specific expense 

export const FILTER_BY_ID_EXPENSE_REQUEST = "FILTER_BY_ID_EXPENSE_REQUEST";
export const FILTER_BY_ID_EXPENSE_SUCCESS = "FILTER_BY_ID_EXPENSE_SUCCESS";
export const FILTER_BY_ID_EXPENSE_FAIL = "FILTER_BY_ID_EXPENSE_FAIL";

// Select Expense
export const SELECTED_EXPENSE_REQUEST = "SELECTED_EXPENSE_REQUEST";
export const SELECTED_EXPENSE_SUCCESS = "SELECTED_EXPENSE_SUCCESS";
export const SELECTED_EXPENSE_FAIL = "SELECTED_EXPENSE_FAIL";

//Delete expense

export const DELETE_EXPENSE_REQUEST = "DELETE_EXPENSE_REQUEST";
export const DELETE_EXPENSE_SUCCESS = "DELETE_EXPENSE_SUCCESS";
export const DELETE_EXPENSE_FAIL = "DELETE_EXPENSE_FAIL";

// Filter expense

export const FILTER_EXPENSE_REQUEST = "FILTER_EXPENSE_REQUEST";
export const FILTER_EXPENSE_SUCCESS = "FILTER_EXPENSE_SUCCESS";
export const FILTER_EXPENSE_FAIL = "FILTER_EXPENSE_FAIL";

export const FILTER_TOTAL_AMOUNT_EXPENSE_BY_CURRENCY_REQUEST = "FILTER_TOTAL_AMOUNT_EXPENSE_BY_CURRENCY_REQUEST";
export const FILTER_TOTAL_AMOUNT_EXPENSE_BY_CURRENCY_SUCCESS = "FILTER_TOTAL_AMOUNT_EXPENSE_BY_CURRENCY_SUCCESS";
export const FILTER_TOTAL_AMOUNT_EXPENSE_BY_CURRENCY_FAIL = "FILTER_TOTAL_AMOUNT_EXPENSE_BY_CURRENCY_FAIL";

// Income 

// Create income

export const CREATE_INCOME_REQUEST = "CREATE_INCOME_REQUEST";
export const CREATE_INCOME_SUCCESS = "CREATE_INCOME_SUCCESS";
export const CREATE_INCOME_FAIL = "CREATE_INCOME_FAIL";

// Get the last 20 income 

export const GET_INCOME_REQUEST = "GET_INCOME_REQUEST";
export const GET_INCOME_SUCCESS = "GET_INCOME_SUCCESS";
export const GET_INCOME_FAIL = "GET_INCOME_FAIL";

// Get a specific income 

export const FILTER_BY_ID_INCOME_REQUEST = "FILTER_BY_ID_INCOME_REQUEST";
export const FILTER_BY_ID_INCOME_SUCCESS = "FILTER_BY_ID_INCOME_SUCCESS";
export const FILTER_BY_ID_INCOME_FAIL = "FILTER_BY_ID_INCOME_FAIL";

//Delete income

export const DELETE_INCOME_REQUEST = "DELETE_INCOME_REQUEST";
export const DELETE_INCOME_SUCCESS = "DELETE_INCOME_SUCCESS";
export const DELETE_INCOME_FAIL = "DELETE_INCOME_FAIL";

// Filter income

export const FILTER_INCOME_REQUEST = "FILTER_INCOME_REQUEST";
export const FILTER_INCOME_SUCCESS = "FILTER_INCOME_SUCCESS";
export const FILTER_INCOME_FAIL = "FILTER_INCOME_FAIL";

// Select Income

export const SELECTED_INCOME_REQUEST = "SELECTED_INCOME_REQUEST";
export const SELECTED_INCOME_SUCCESS = "SELECTED_INCOME_SUCCESS";
export const SELECTED_INCOME_FAIL = "SELECTED_INCOME_FAIL";

export const FILTER_TOTAL_AMOUNT_INCOME_BY_CURRENCY_REQUEST = "FILTER_TOTAL_AMOUNT_INCOME_BY_CURRENCY_REQUEST";
export const FILTER_TOTAL_AMOUNT_INCOME_BY_CURRENCY_SUCCESS = "FILTER_TOTAL_AMOUNT_INCOME_BY_CURRENCY_SUCCESS";
export const FILTER_TOTAL_AMOUNT_INCOME_BY_CURRENCY_FAIL = "FILTER_TOTAL_AMOUNT_INCOME_BY_CURRENCY_FAIL";

// Notification 

// Create notification

export const CREATE_NOTIFICATION_REQUEST = "CREATE_NOTIFICATION_REQUEST";
export const CREATE_NOTIFICATION_SUCCESS = "CREATE_NOTIFICATION_SUCCESS";
export const CREATE_NOTIFICATION_FAIL = "CREATE_NOTIFICATION_FAIL";

// Get the last 20 notification 

export const GET_NOTIFICATION_REQUEST = "GET_NOTIFICATION_REQUEST";
export const GET_NOTIFICATION_SUCCESS = "GET_NOTIFICATION_SUCCESS";
export const GET_NOTIFICATION_FAIL = "GET_NOTIFICATION_FAIL";

// Get a specific notification 

export const FILTER_BY_ID_NOTIFICATION_REQUEST = "FILTER_BY_ID_NOTIFICATION_REQUEST";
export const FILTER_BY_ID_NOTIFICATION_SUCCESS = "FILTER_BY_ID_NOTIFICATION_SUCCESS";
export const FILTER_BY_ID_NOTIFICATION_FAIL = "FILTER_BY_ID_NOTIFICATION_FAIL";

//Delete notification

export const DELETE_NOTIFICATION_REQUEST = "DELETE_NOTIFICATION_REQUEST";
export const DELETE_NOTIFICATION_SUCCESS = "DELETE_NOTIFICATION_SUCCESS";
export const DELETE_NOTIFICATION_FAIL = "DELETE_NOTIFICATION_FAIL";

// Filter notification

export const FILTER_NOTIFICATION_REQUEST = "FILTER_NOTIFICATION_REQUEST";
export const FILTER_NOTIFICATION_SUCCESS = "FILTER_NOTIFICATION_SUCCESS";
export const FILTER_NOTIFICATION_FAIL = "FILTER_NOTIFICATION_FAIL";

//Pay 

export const PAYMENT_REQUEST = "PAYMENT_REQUEST";
export const PAYMENT_SUCCESS = "PAYMENT_SUCCESS";
export const PAYMENT_FAIL = "PAYMENT_FAIL";

